FROM ubuntu:noble@sha256:1e622c5f073b4f6bfad6632f2616c7f59ef256e96fe78bf6a595d1dc4376ac02

RUN apt update && apt install -y fuse3 openssh-server
RUN mkdir /run/sshd && chmod 0755 /run/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]