services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${HOST}
      - DOCKER_MODS=ghcr.io/ben-pearce/remote-ffmpeg-docker-mod:latest
      - REMOTE_FFMPEG_USER=user
      - REMOTE_FFMPEG_HOST=remote-host
      - REMOTE_FFMPEG_BINARY=/usr/lib/jellyfin-ffmpeg/ffmpeg
    volumes:
      - ./config:/config
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
