FROM remote-ffmpeg-mod AS mod
FROM lscr.io/linuxserver/baseimage-alpine:3.23-524cf2a8-ls5@sha256:4caa670c0e273161cec0d29b3652d5bc0c1d62b8b0dfba9f51c2d455c5dd71a7

RUN apk add ffmpeg openssh socat bash flock

COPY --from=mod / /
