FROM remote-ffmpeg-mod AS mod
FROM ghcr.io/linuxserver/jellyfin:10.10.7@sha256:0844d7504c018b0b0b898914a3c48d9dfa76d8f51ac49d8c66a1108944743fe4

RUN apt update && apt install -y openssh-client openssh-server socat

COPY --from=mod / /
