FROM remote-ffmpeg-mod AS mod
FROM ghcr.io/linuxserver/jellyfin:10.11.4@sha256:5cdc58132f8ef832a8910f732d3fe0144b4f9d091fe6f5409fb1b75d787c1be8

RUN apt update && apt install -y openssh-client openssh-server socat

COPY --from=mod / /
