FROM ubuntu:noble-20260210.1@sha256:d1e2e92c075e5ca139d51a140fff46f84315c0fdce203eab2807c7e495eff4f9

RUN apt update && apt install -y fuse3 openssh-server
RUN mkdir /run/sshd && chmod 0755 /run/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]