FROM remote-ffmpeg-mod AS mod
FROM lscr.io/linuxserver/baseimage-alpine:3.24-f4dd099d-ls7@sha256:34c19f3f2345f1d231784e78db95e330ce198c267b10fe8daa88b6bded30636b

RUN apk add ffmpeg openssh socat bash flock

COPY --from=mod / /
