FROM ubuntu:noble@sha256:66460d557b25769b102175144d538d88219c077c678a49af4afca6fbfc1b5252

RUN apt update && apt install -y fuse3 openssh-server
RUN mkdir /run/sshd && chmod 0755 /run/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]