FROM remote-ffmpeg-mod AS mod
FROM ghcr.io/linuxserver/baseimage-alpine:3.22@sha256:c2c6821f008925009f2c7bd87bfcb777d5062509db49670c2693e54835de95d0

RUN apk add ffmpeg openssh socat bash flock

COPY --from=mod / /
