FROM ubuntu:noble@sha256:353675e2a41babd526e2b837d7ec780c2a05bca0164f7ea5dbbd433d21d166fc

RUN apt update && apt install -y fuse3 openssh-server
RUN mkdir /run/sshd && chmod 0755 /run/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]