name: 🧪 Run Tests

on:
  pull_request:
    branches:
      - main
      - release/*
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🐳 Use Docker
        uses: actions-hub/docker@f5fdbfc3f9d2a9265ead8962c1314108a7b7ec5d # v1.0.3
        env:
          SKIP_LOGIN: true

      - name: 🧪 Run bash_unit tests
        run: sudo ./bash_unit test/test_*.sh